### ISSUE TITLE
Add a "failed" message if the player can't teleport throught the portal

### ISSUE THREAD

**Issue by Sup33r** [asnover/Transfer-Service#7]
Im not 100% sure, and please correct me if im wrong, but i don't think there is any way right now for the client side plugin to know that the portal interaction has failed. I would like to have it display a message in chat, like "The desired server is currently offline", or "Failed to connect: You don't have permission to join this server" or something along those lines. I feel that it would make it easier to know for users why their teleportation failed, and to rule out bad connection, lag etc.

It would also be cool if the error on the velocity side would be cleaned up a bit, because if the current "message" can be a bit spammy:
`java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:25566
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at me.snover.MessageReceivedHandler.onMessageReceived(MessageReceivedHandler.java:56)
	at me.snover.Lmbda$10.execute(Unknown Source)
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676)
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by asnover** [comment]
What exactly did you do to produce this exception? Was the server just not bound to that address? (Yes, the server being offline counts as not being bound to the address).

Edit: Nevermind. I see it in there.
